version: "3"

services:

  elasticsearch:
    image: quay.io/giantswarm/elasticsearch-oss:6.1.1
    ports:
      - 9200:9200

  kibana:
    image: quay.io/giantswarm/curator:latest
    depends_on:
      - elasticsearch
