orbs:
  architect: giantswarm/architect@0.4.5

version: 2.1
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./architect
        ./architect version

    - run: make test
    - run: ./architect build
    - run: ./architect publish --pipeline=false --channels=wip-${CIRCLE_SHA1}

    - store_test_results:
        path: /tmp/results

    - persist_to_workspace:
        root: .
        paths:
        - ./curator
        - ./architect

  deploy:
    machine: true
    steps:
    - checkout
    - attach_workspace:
        at: .
    - deploy:
        command: |
            ./architect deploy

workflows:
  build:
    jobs:
      - build

      # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker-legacy:
          name: push-curator-to-aliyun-master
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/curator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master
      - deploy:
          name: deploy
          requires:
            - push-curator-to-aliyun-master
          filters:
            branches:
              only: master
